#!/bin/bash

CONFIG="$1"

DISPATCHERDIR=/home/armen/projects/irancell/public_html
PHP=/usr/bin/php

if [ -e "$CONFIG" ]
then
    . "$CONFIG"
else
    if [ -e /etc/default/aragmq.cfg ]
    then
        . /etc/default/aragmq.cfg
    fi
fi

clean_up()
{
    kill -SIGUSR1 $SLAVE
    exit
}

trap clean_up SIGHUP SIGINT SIGTERM

while [ 1 ]
do
    cd $DISPATCHERDIR
    $PHP index.php $SERVER/common/keep_alive &
    SLAVE=$!
    wait $SLAVE
done
